name: jansuvidha
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.6.0
  http: ^1.3.0
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.0
  cupertino_icons: ^1.0.8
  share_plus: ^7.0.0
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  device_info_plus: ^10.1.0
  url_launcher: ^6.3.0
  google_maps_flutter: ^2.12.1
  flutter_polyline_points: ^2.1.0
  intl: ^0.18.1

  # Firebase packages
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  cloud_firestore: ^4.8.5
  firebase_dynamic_links: ^5.4.9


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - images/Logo.png
    - images/Call4x.png
    - images/pfp.webp
    - images/google_logo.png
    - images/digilocker_logo.png