name: jansuvidha
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.6.0
  http: ^1.1.0
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.0
  # Updated these problematic dependencies to newer versions
  image_picker: ^1.0.4
  permission_handler: ^11.0.0
  cupertino_icons: ^1.0.8
  device_info_plus: ^9.0.0
 
  geolocator: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - images/Logo.png
    - images/Call4x.png
    - images/pfp.webp